### ISSUE TITLE
Issue with language other than english

### ISSUE THREAD

**Issue by mehulshah143** [HongliYu/DPColorfulTags-Swift#2]
When we use language other than english the label size expands rendomly and the text does not get aligned in the centre of the label.
Please suggest what to be done .. As i'm on the verge of releasing my application. Cant afford to change the library at this point

Please find the attachment which shows the issue when i swift my app language from english to Farsi.
Eagerly waiting for a positive reply.

Thank you..!!

![simulator screen shot 10-nov-2017 3 24 56 pm](https://user-images.githubusercontent.com/17250699/32653130-bd8d11b8-c62c-11e7-83a7-8cca0c421ec6.png)
![simulator screen shot 10-nov-2017 3 41 22 pm](https://user-images.githubusercontent.com/17250699/32653159-d32a80fa-c62c-11e7-883b-d5e4a169bd8a.png)

**Comment by HongliYu** [comment]
@mehulshah143 A little bit busy yesterday, now I am looking into the issue. I think that I have solved the vertical black line bug in the last release version, anyway let me double check the problem, and add support for multi-language problem as well.

**Comment by HongliYu** [comment]
Actually this bug can not happened in other languages but Persian, because its writing direction is different from English, German, Chinese. And there is a bug in UILabel attributedText with Persian by Apple OS. Anyway, I use some tricks to solve the problem. Check the latest version, hope it's useful :) @mehulshah143 
![simulator screen shot - iphone x - 2017-11-12 at 01 33 55](https://user-images.githubusercontent.com/5026793/32692671-e7a06c4c-c6e1-11e7-99a5-1e57ffb88d7b.png)

**Comment by mehulshah143** [comment]
Thanx a lot HongliYu.
I will test it by tomorrow. Actually it's midnight 1 A.M here in India
right now.
Thank you for your help.
Will let you know once implemented latest version.

Thank you..!!

**Comment by HongliYu** [comment]
Good night, Have a nice sleep. @mehulshah143 Hope you can release the app in time :)
